version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "00:30"
    target-branch: "main"
    cooldown:
      default-days: 10
    assignees:
      - "hibare"
    groups:
      actions:
        patterns:
          - "*"

  # Maintain dependencies for Go mods
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "00:30"
    target-branch: "main"
    cooldown:
      default-days: 10
    assignees:
      - "hibare"
    allow:
      - dependency-type: "direct"
    groups:
      go:
        patterns:
          - "*"

  # Maintain version for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "00:30"
    target-branch: "main"
    cooldown:
      default-days: 10
    assignees:
      - "hibare"
    groups:
      docker:
        patterns:
          - "*"

  # Maintain dependencies for npm (web frontend)
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "00:30"
    target-branch: "main"
    cooldown:
      default-days: 10
    assignees:
      - "hibare"
    groups:
      npm:
        patterns:
          - "*"
